[package]
name = "Browser"
version = "0.1.0"
edition = "2024"

[dependencies]
socket2 = "0.6"
rustls = "0.23"
webpki-roots = "1.0.3"

pixels = "0.15"
winit = "0.29"
winit_input_helper = "0.16"
ab_glyph = "0.2"
rustybuzz = "0.20"
font-kit = "0.14"
